services:
  - type: web
    name: meligo
    runtime: docker
    repo: https://github.com/ArmanRajabi8/MeliGo.git
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /healthz
    envVars:
      - key: ConnectionStrings__MeliGoContext
        sync: false
      - key: Jwt__Key
        generateValue: true
      - key: Jwt__Issuer
        value: meligo
      - key: Jwt__Audience
        value: meligo-web
